### ISSUE TITLE
Aliview inserts column break every 60 characters in very large MSA (with more than 100,000 sequences) 

### ISSUE THREAD

**Issue by Steven-Kemp** [AliView/AliView#92]
Hi there,

AliView seems to be exhibiting some weird behaviour with extremely long MSA. I gave it more memory by editing the plist (to use 4Gb RAM) but it seems to be breaking every 60 characters with a blank column... when transating to AA view, it obviously causes massive frameshifts, because there is a gap every 60 characters now.

I double checked the fasta file in TextEdit and there's no gaps. Is this a viewer issues specifically?

Best wishes,
Steve

![Screenshot 2020-11-29 at 23 05 48](https://user-images.githubusercontent.com/50207325/100556119-c3b80680-3297-11eb-811a-9c80297cfa28.png)

**Comment by willfischer** [comment]
Jumping in here, because I’ve had similar problems.

Odds are that there is an invisible extra character at the end of each line (probably the fasta file came from a windows-based system?).

You’re on a mac, right?  In a terminal window, do this:

tr -s \\r\\n <smb://r//n> \\n\\n <smb://n//n> < FILENAME.fasta > FILENAME.new.fasta

This will convert any number of successive carriage-return and newline characters (e.g. the paired CR/NL DOS end-of-line) to a single newline (ascii 12), which is what a unix system expects. So FILENAME.new.fasta should open fine … if not, you have a different problem, and have wasted a few keystrokes.

Good luck,

— Will Fischer

______________________ 
Will Fischer

net: wfischer@lanl.gov
cell: 505-577-0592

Group T-6, Theoretical Biology
Los Alamos National Laboratory

**Comment by Steven-Kemp** [comment]
Hi Will,

Thanks for the reply - no the fasta files were made on the same Mac I'm using to examine them. I broke a huge fasta into 10 pieces to perform individual alignments (which I could then cat *.fasta > all.fasta). If you can two or three of these together, it opens as expected. Any more than that, it starts to introduce the issue I encountered above.

I did indeed go ahead and attempt to remove carriage-returns and newline characters, but there wasn't any and my issue still persists :-( I strongly suspect it's to do with the number of characters in the file perhaps. I'll download SeaView and see if the issue still persists there.

Best wishes,
Steve

**Comment by andersla** [comment]
Hi Steve, do you have an example of a file where this happens to see what might be the issue?

**Comment by Steven-Kemp** [comment]
Hi @andersla,

Sorry for the delay - I think I've found the culprit. I recently acquired a new Mac with much more memory. I usually manually edited the plist file to give Aliview roughly 10Gb memory, on my laptop I only have 8gb, on my Mac I have 64Gb. 

Opening a msa of 300000 sequences with average length of 30kb and assigning the AliView 12Gb memory seems to have fixed my issue - there's no no random gaps throughout.

I'm not allowed to share the file I'm using sadly due to an NDA, but potentially an issue with either the alignment (made using MAFFT) or it not being able to index all sequences correctly?

Best wishes,
Steve
